<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.16.osoe-925" />

  <PropertyGroup>
    <Title>Lombiq Marketing - URL Shortener for Orchard Core</Title>
    <CopyrightYear>2026</CopyrightYear>
    <Description>Create short URLs that redirect to long URLs and provide extensibility for handling a redirect event.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Marketing;UrlShortener;ShortUrl;Redirect</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Marketing</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Marketing/blob/dev/Lombiq.Marketing.UrlShortener/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentFields" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Contents" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Title" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.Marketing\Lombiq.Marketing.csproj" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.16.osoe-925" />

</Project>
