using Atata;
using Lombiq.Tests.UI.Extensions;
using Lombiq.Tests.UI.Services;
using Microsoft.AspNetCore.WebUtilities;
using OpenQA.Selenium;
using Shouldly;
using System;
using System.Threading.Tasks;
using LogLevel = Microsoft.Extensions.Logging.LogLevel;

namespace Lombiq.Marketing.Tests.UI.Extensions;

public static class TestCaseUITestContextExtensions
{
    private const string TestPirschScript = "<script defer=\"\" id=\"pianjs\" data-code=\"test\" data-dev=\"test\"></script>";
    private const string TestPirschDataDev = "lombiq-marketing";

    public static async Task TestShortUrlManagementAsync(this UITestContext context)
    {
        const string manualTitle = "Marketing Short URL Test";
        const string shortUrl = "/jmp/marketing-short-url";
        const string updatedShortUrl = "/jmp/marketing-short-url-updated";

        await context.EnableFeatureDirectlyAsync("Lombiq.Marketing");
        await context.EnableFeatureDirectlyAsync("Lombiq.Marketing.UrlShortener");

        await context.SignInDirectlyAndGoToDashboardAsync();

        await context.ClickReliablyOnByLinkTextAsync("Tools");
        await context.ClickReliablyOnByLinkTextAsync("Short URLs");
        await context.ClickReliablyOnByLinkTextAsync("New Short URL");

        await context.FillShortUrlFieldAsync("ShortUrlPart_ShortUrl_Text", shortUrl);
        await context.FillShortUrlFieldAsync("ShortUrlPart_DestinationUrl_Text", "/");

        await context.ClickReliablyOnByLinkTextAsync("UTM Parameters");
        await context.FillShortUrlFieldAsync("UtmPart_UtmSource_Text", "newsletter");
        await context.FillShortUrlFieldAsync("UtmPart_UtmMedium_Text", "email");
        await context.FillShortUrlFieldAsync("UtmPart_UtmCampaign_Text", "spring-sale");
        await context.FillShortUrlFieldAsync("UtmPart_UtmContent_Text", "hero-banner");
        await context.FillShortUrlFieldAsync("UtmPart_UtmTerm_Text", "orchard-core");

        await context.ClickPublishAsync();
        context.ShouldBeSuccess();

        // Verify that the display text was auto-generated with UTM parameters and the short URL arrow pattern.
        var autoGeneratedTitlePrefix =
            "/?utm_source=newsletter&utm_medium=email&utm_campaign=spring-sale&utm_content=hero-banner&utm_term=orchard-core";
        var autoGeneratedTitle = autoGeneratedTitlePrefix + " \u2190 " + shortUrl;
        var editLinkBy = By.LinkText(autoGeneratedTitle);
        context.Driver.Exists(editLinkBy);

        // Testing cloning. The cloned item should have a different short URL and auto-generated display text.
        await context.FilterOnAdminAsync(autoGeneratedTitlePrefix);
        await context.ClickReliablyOnAsync(By.XPath("//button[contains(.,'Actions')]"));
        await context.ClickReliablyOnByLinkTextAsync("Clone");

        var titles = context.GetAll(By.PartialLinkText(autoGeneratedTitlePrefix));
        titles.Count.ShouldBe(2);
        titles[0].Text.ShouldStartWith(autoGeneratedTitlePrefix);
        titles[1].Text.ShouldStartWith(autoGeneratedTitlePrefix);
        titles[0].Text.ShouldNotBe(titles[1].Text);

        await titles[0].ClickReliablyAsync(context);
        var firstShortUrl = context.Get(By.Id("ShortUrlPart_ShortUrl_Text")).GetAttribute("value");

        await context.BackAsync();
        await titles[1].ClickReliablyAsync(context);
        var secondShortUrl = context.Get(By.Id("ShortUrlPart_ShortUrl_Text")).GetAttribute("value");

        firstShortUrl.ShouldNotBeNullOrWhiteSpace();
        secondShortUrl.ShouldNotBeNullOrWhiteSpace();
        firstShortUrl.ShouldStartWith("/jmp/");
        secondShortUrl.ShouldStartWith("/jmp/");
        firstShortUrl.ShouldNotBe(secondShortUrl);

        // Now add the title.
        await context.BackAsync();
        await context.ClickReliablyOnAsync(editLinkBy);
        // No need to repeatedly go through the UI to reach the editor from now on.
        var editorUri = context.GetCurrentUri();
        await context.FillContentItemTitleAsync(manualTitle);
        await context.ClickPublishAsync();
        context.ShouldBeSuccess();

        // Verify the display text now uses the title instead of the auto-generated URL.
        await context.GoToContentItemListAsync("ShortUrl");
        context.Exists(By.LinkText(manualTitle));

        // Verify the redirection.
        await context.GoToRelativeUrlAsync(shortUrl, onlyIfNotAlreadyThere: false);
        var redirectedUri = context.GetCurrentUri();
        redirectedUri.AbsolutePath.ShouldBe("/");
        QueryHelpers.ParseQuery(redirectedUri.Query).ShouldBeEmpty();

        // Update the short URL.
        await context.GoToAbsoluteUrlAsync(editorUri);
        await context.FillShortUrlFieldAsync("ShortUrlPart_ShortUrl_Text", updatedShortUrl);
        await context.ClickReliablyOnByLinkTextAsync("UTM Parameters");
        await context.FillShortUrlFieldAsync("UtmPart_UtmCampaign_Text", "summer-sale");
        await context.ClickPublishAsync();
        context.ShouldBeSuccess();

        // Verify the redirection still happens.
        await context.GoToRelativeUrlAsync(updatedShortUrl, onlyIfNotAlreadyThere: false);
        var updatedUri = context.GetCurrentUri();
        updatedUri.AbsolutePath.ShouldBe("/");
        QueryHelpers.ParseQuery(updatedUri.Query).ShouldBeEmpty();

        // Verify delete.
        await context.GoToContentItemListAsync("ShortUrl");
        await context.FilterOnAdminAsync(manualTitle);
        await context.ClickReliablyOnAsync(By.XPath("//button[contains(.,'Actions')]"));
        await context.ClickReliablyOnByLinkTextAsync("Delete");
        await context.ClickModalOkAsync();
        context.ShouldBeSuccess();
        context.Exists(By.XPath($"//a[normalize-space()='{manualTitle}']").Safely()).ShouldBeFalse();

        await context.GoToRelativeUrlAsync(updatedShortUrl, onlyIfNotAlreadyThere: false);
        context.GetCurrentUri().AbsolutePath.ShouldBe(updatedShortUrl);
        await context.GoToRelativeUrlAsync(shortUrl, onlyIfNotAlreadyThere: false);
        context.GetCurrentUri().AbsolutePath.ShouldBe(shortUrl);
    }

    public static async Task TestPirschClientSideTrackingAutomaticInjectionAsync(this UITestContext context)
    {
        AssertPirschSnippet(context.Driver.PageSource, "pianjs", "test");

        await context.SignInDirectlyAndGoToDashboardAsync();

        await context.ClickReliablyOnByLinkTextAsync("Configuration");
        await context.ClickReliablyOnByLinkTextAsync("Settings");
        await context.ClickReliablyOnByLinkTextAsync("Marketing");
        await context.ClickReliablyOnByLinkTextAsync("Pirsch");

        await context.ClickAndFillInWithRetriesAsync(
            By.Id("ISite_PirschSettings_ClientSideCodeSnippet"),
            "<script defer=\"\" id=\"pianjs\" data-code=\"test\"></script>");
        await context.ClickReliablyOnSubmitAsync();
        context.ShouldBeSuccess();

        await context.GoToHomePageAsync();

        AssertPirschSnippet(context.Driver.PageSource, "pianjs", TestPirschDataDev);

        await context.GoToAdminRelativeUrlAsync("/Settings/PirschSettings");
        await context.ClickAndFillInWithRetriesAsync(By.Id("ISite_PirschSettings_DataDev"), "newDataDev");
        await context.ClickReliablyOnSubmitAsync();
        context.ShouldBeSuccess();

        await context.GoToHomePageAsync();

        AssertPirschSnippet(context.Driver.PageSource, "pianjs", "newDataDev");
    }

    public static void SetPirschClientTrackerConfiguration(this OrchardCoreUITestExecutorConfiguration configuration)
    {
        configuration.AssertAppLogsAsync = app =>
            app.LogsShouldNotContainAsync(logEntry => IsUnexpectedAppLog(logEntry), configuration.TestCancellationToken);

        configuration.WithIgnoreExpectedNotFoundResponseFilter("/secret-sauce/pv");
        configuration.OrchardCoreConfiguration.BeforeAppStart +=
            (_, argumentsBuilder) =>
            {
                argumentsBuilder
                    .AddWithValue(
                        "OrchardCore:Lombiq_Marketing:Pirsch:ClientSideCodeSnippet",
                        TestPirschScript)
                    .AddWithValue(
                        "OrchardCore:Lombiq_Marketing:Pirsch:DataDev",
                        TestPirschDataDev);

                return Task.CompletedTask;
            };
    }

    public static void SetShortUrlConfiguration(this OrchardCoreUITestExecutorConfiguration configuration)
    {
        configuration.AssertAppLogsAsync = app =>
            app.LogsShouldNotContainAsync(logEntry => IsUnexpectedAppLog(logEntry), configuration.TestCancellationToken);

        configuration.WithIgnoreExpectedNotFoundResponseFilter("/jmp/marketing-short-url");
        configuration.WithIgnoreExpectedNotFoundResponseFilter("/jmp/marketing-short-url-updated");
    }

    private static bool IsUnexpectedAppLog(IApplicationLogEntry logEntry) =>
        logEntry.Level >= LogLevel.Error &&
        !IsExpectedPirschShortUrlError(logEntry);

    // Since we don't want to send real data, we have to suppress these.
    private static bool IsExpectedPirschShortUrlError(IApplicationLogEntry logEntry) =>
        (logEntry.Category == "Lombiq.Marketing.Pirsch.Services.PirschApiClient" &&
        logEntry.Message.ContainsOrdinalIgnoreCase("Cannot send a request to Pirsch API because the client secret is not configured")) ||
        (logEntry.Category == "Lombiq.Marketing.Pirsch.Services.PirschShortUrlHitHandler" &&
        logEntry.Message.ContainsOrdinalIgnoreCase("Failed to send a hit to Pirsch API for the tracked target URL:"));

    public static Task FillShortUrlFieldAsync(this UITestContext context, string id, string value) =>
        context.ClickAndFillInWithRetriesAsync(
            By.Id(id),
            value);

    private static void AssertPirschSnippet(
        string pageSource,
        string id,
        string dataDev)
    {
        pageSource.ShouldContain($"id=\"{id}\"");
        pageSource.ShouldContain("src=\"/secret-sauce/sauce.js\"");
        pageSource.ShouldContain("data-hit-endpoint=\"/secret-sauce/pv\"");
        pageSource.ShouldContain("data-event-endpoint=\"/secret-sauce/e\"");
        pageSource.ShouldContain("data-session-endpoint=\"/secret-sauce/s\"");
        pageSource.ShouldContain("data-code=\"test\"");
        pageSource.ShouldContain($"data-dev=\"{dataDev}\"");
    }
}
